# K1NGB0B Recon Script Configuration File
# Author: Arafat-X30N

# Tool configurations
tools:
  assetfinder:
    enabled: true
    timeout: 300
    retries: 3
    additional_args: []
  
  subfinder:
    enabled: true
    timeout: 300
    retries: 3
    additional_args: []
  
  crt_sh:
    enabled: true
    timeout: 60
    retries: 3
    additional_args: []
  
  wayback:
    enabled: true
    timeout: 120
    retries: 3
    additional_args: []
  
  httpx:
    enabled: true
    timeout: 10
    retries: 3
    additional_args: []

# Output settings
output:
  base_dir: "."
  create_reports: true
  save_raw_data: true
  compress_results: false
  format: "txt"

# HTTP settings
http:
  timeout: 10
  retries: 3
  threads: 50
  user_agent: "K1NGB0B-Recon/2.0"

# General settings
verbose: false
debug: false
